services:
    geyser:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Voidex-MC
        ports:
            - "25565:25565"
            - "19132:19132/udp"
        volumes:
            - ./app:/app
        stdin_open: true
        tty: true
