version: "3.8"

services:
    geyser:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: minecraft-geyser
        ports:
            - "25565:25565"
            - "19132:19132/udp"
        volumes:
            - ./app:/app/app
        stdin_open: true
        tty: true
